name: Lint Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint shellcheck

      - name: Lint YAML files
        run: |
          echo "Checking YAML files..."
          yamllint --strict ./*.yaml

      - name: Lint shell scripts
        run: |
          echo "Checking shell scripts..."
          find . -type f -name "*.sh" -exec shellcheck {} +